/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import civitas.Casilla;
import civitas.CasillaCalle;
import civitas.CasillaSorpresa;

/**
 *
 * @author Jesus Martin
 */
public class CasillaPanel extends javax.swing.JPanel {
    Casilla casillaActual;
    /**
     * Creates new form CasillaPanel
     */
    public CasillaPanel() {
        initComponents();
    }
    
    protected void setCasilla( Casilla casilla){
        this.casillaActual = (Casilla) casilla;
        if(casilla.getClass() == CasillaCalle.class){
            CasillaCalle calle = (CasillaCalle) casilla;
            textTipo.setText("Calle");
            if(casilla.tienePropietario()){
                textPropietario.setVisible(true);
                propietario.setVisible(true);
                textPrecioAlquiler.setVisible(true);
                precioAlquiler.setVisible(true);
                textPropietario.setText(calle.getPropietario().getNombre());
                textPrecioAlquiler.setText(Float.toString(calle.getPrecioAlquilerCompleto()));
                textPrecioCompra.setVisible(false);
                precioCompra.setVisible(false);
            }else{
                textPrecioCompra.setVisible(true);
                precioCompra.setVisible(true);
                textPrecioCompra.setText(Float.toString(calle.getPrecioCompra()));
                textPropietario.setVisible(false);
                propietario.setVisible(false);
                textPrecioAlquiler.setVisible(false);
                precioAlquiler.setVisible(false);
            }
        }else if(casilla.getClass() == CasillaSorpresa.class){
            textTipo.setText("Sorpresa");
            textPropietario.setVisible(false);
            propietario.setVisible(false);
            textPrecioAlquiler.setVisible(false);
            precioAlquiler.setVisible(false);
            textPrecioCompra.setVisible(false);
            precioCompra.setVisible(false);
        }else{
            textTipo.setText("Descanso");
            textPropietario.setVisible(false);
            propietario.setVisible(false);
            textPrecioAlquiler.setVisible(false);
            precioAlquiler.setVisible(false);
            textPrecioCompra.setVisible(false);
            precioCompra.setVisible(false);
        }
        
        textNombre.setText(casilla.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipo = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        precioCompra = new javax.swing.JLabel();
        propietario = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        textPropietario = new javax.swing.JTextField();
        textTipo = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        textPrecioCompra = new javax.swing.JTextField();
        textPrecioAlquiler = new javax.swing.JTextField();
        precioAlquiler = new javax.swing.JLabel();

        tipo.setText("Tipo");

        nombre.setText("Nombre");

        precioCompra.setText("Precio Compra");

        propietario.setText("Propietario");

        titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titulo.setText("Casilla Actual");

        textPropietario.setEditable(false);

        textTipo.setEditable(false);
        textTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTipoActionPerformed(evt);
            }
        });

        textNombre.setEditable(false);

        textPrecioCompra.setEditable(false);

        textPrecioAlquiler.setEditable(false);

        precioAlquiler.setText("Precio Alquiler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(precioCompra)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tipo)
                                    .addGap(34, 34, 34)))
                            .addComponent(precioAlquiler)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(nombre))
                            .addComponent(propietario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textPropietario, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(textPrecioAlquiler, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textTipo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textPrecioCompra, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(titulo))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo)
                    .addComponent(textTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioCompra)
                    .addComponent(textPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioAlquiler)
                    .addComponent(textPrecioAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(propietario))
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTipoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel precioAlquiler;
    private javax.swing.JLabel precioCompra;
    private javax.swing.JLabel propietario;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textPrecioAlquiler;
    private javax.swing.JTextField textPrecioCompra;
    private javax.swing.JTextField textPropietario;
    private javax.swing.JTextField textTipo;
    private javax.swing.JLabel tipo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
